---
- hosts: master
  tasks:

  - name: install git
    package: 
      name: git
      state: present

  - name: clone awx repo
    git:
      repo: https://github.com/ansible/awx.git
      dest: /opt/awx
      update: no
      
  - name: apt update
    apt:
      update_cache: yes

  - name: install pip
    package:
      name: python3-pip
      state: present
      
  - name: install docker python
    pip:
      name: docker

  - name: install make
    package:
      name: make
      state: present

  - name: install ansible
    package: 
      name: ansible
      state: present

  - name: install nodejs
    package: 
      name: nodejs
      state: present

  - name: install npm
    package:
      name: npm
      state: present

  - name: install helm
    command: snap install helm --classic
    args:
      creates: /snap/bin/helm

  - name: copy rbac-helm.yml
    copy:
      dest: /home/vagrant/rbac-helm.yml
      content: |
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: tiller
          namespace: kube-system
        ---
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: tiller
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
        - kind: ServiceAccount
          name: tiller
          namespace: kube-system

  - name: create tiller serviceaccount in k8s
    command: kubectl --kubeconfig /home/vagrant/.kube/config apply -f /home/vagrant/rbac-helm.yml
  
  - name: init helm
    command: helm init --service-account tiller --history-max 200 --kubeconfig /home/vagrant/.kube/config

  - name: copy awx inventory
    copy: 
      src: awx-inventory
      dest: /opt/awx/installer/inventory
