---
- name: install docker
  package:
    name: docker.io
    state: latest

- name: download k8s
  command: wget -O /home/vagrant/k8s-server-1.14.tgz https://dl.k8s.io/v1.14.0/kubernetes-server-linux-amd64.tar.gz
  args:
    creates: /home/vagrant/k8s-server-1.14.tgz

- name: unzip k8s
  command: tar tfz /home/vagrant/k8s-server-1.14.tgz -C /home/vagrant/
  args:
    creates: /home/vagrant/kubernetes/server/bin/kubeadm

- name: run kubeadm
  command: /home/vagrant/kubernetes/server/bin/kubeadm init --pod-network-cidr 192.168.0.0/16 --apiserver-advertise-address {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
  args: 
    creates: /etc/kubernetes/admin.conf

- name: create /home/vagrant/.kube
  file:
    path: /home/vagrant/.kube
    state: directory

- name: copy kube config
  command: cp /etc/kubernetes/admin.conf /home/vagrant/.kube/config
  args:
    creates: /home/vagrant/.kube/config

- name: enable kubelet
  systemd: kubelet
    state: started
    enabled: yes
    
- name: list token
  shell: /home/vagrant/kubernetes/server/bin/kubeadm token list > /home/vagrant/token
  args:
    creates: /home/vagrant/token
  
- name: fetch token
  fetch: 
    src: /home/vagrant/token
    dest: /tmp/fetched





